server:
  port: 8082
# 应用名称：client
spring:
  application:
    name: provider-other
  security:
    user:
      name: root
      password: root

  #据库连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/db_project?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Dx19800602Fb
    driver-class-name: com.mysql.cj.jdbc.Driver

#关联**Mapper.xml 文件
mybatis:
  mapper-locations: classpath:com/provider_other/mapper/*.xml
  config-location: classpath:mybatis.cfg.xml

# 注册到我们本地的eureka注册中心，端口是8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
