server:
  port: 8082
# 应用名称：client
spring:
  application:
    name: provider-other
  security:
    user:
      name: root
      password: root
# 注册到我们本地的eureka注册中心，端口是8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
