server:
  port: 8085

#指定当前服务的名称会注册到注册中心
spring:
  application:
    name: consumer-feign

#指定服务注册中心的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

#feign拦截器的配置
feign:
  client:
    config:
      provider-other:
        requestInterceptors:
          - com.feign.FeignRequestInterceptor